name: Build on commit

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        binaryname: [FindProcessesWithNamedPipes]

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1
        
      - name: Restore NuGet packages
        run: nuget restore

      - name: Build Solution
        run: |
          MSBuild.exe /p:Configuration=Release

      - name: dir
        run: dir
